const slugify = (str: string) =>
  str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const imageMap: Record<string, string | undefined> = {
  "Aveeno Baby Daily Moisture Lotion": "/images/aveenababylotion.webp",
  "Baby Bath Tub": "/images/babybathtub.webp",
  "Gentle Baby Body Wash": "/images/babycleansing.webp",
  "Baby Grooming Kit": "/images/babygroomingkit.webp",
  "Silicone Baby Pacifiers (2-Pack)": "/images/babypacifiers.webp",
  "Baby Sunscreen SPF 50": "/images/babysunscreen.webp",
  "Baby Crinkle Book with Teether": "/images/bookwithtoys.webp",
  "Honest Shampoo & Body Wash": "/images/Honestshampoo&bodywash.webp",
  "Johnsons Baby Powder": "/images/johnsonsbabypowder.webp",
  "Soft Baby Hair Brush & Comb": "/images/softcomb.webp",
  "Tear-Free Baby Shampoo": "/images/tearfreebabyshampoo.webp",
  "Digital Baby Thermometer": "/images/thermometer.webp",
  "Vapor Bath Drops": "/images/vaporbathdrops.webp",
  "Soothing Baby Bath Soak": "/images/shampoobath.webp",
  "Stainless Steel Cookware Set": "/images/stainlessteelcookwareset.webp",
  "Smart Coffee Maker": "/images/smartcofeemaker.webp",
  "Air Fryer XL": "/images/airfryerXL.webp",
  "Premium Knife Set": "/images/premiumknifeset.webp",
  "Stand Mixer Pro": "/images/standmixerpro.webp",
  "Bamboo Cutting Board Set": "/images/bamboocuttingboardset.webp",
  "Food Storage Container": "/images/glassfoodstoragecontainer.webp",
  "Electric Kettle": "/images/electrickettel.webp",
  "Silicone Baking Mats": "/images/siliconebakingmats.webp",
  "Kitchen Scale Digital": "/images/kitchenscaledigital.webp",
  "Electric Toothbrush": "/images/electric_tootbrush.webp",
  "Water Flosser": "/images/waterflosser.webp",
  "Digital Body Scale": "/images/digitalbodyscale.webp",
  "Essential Oil Diffuser": "/images/essentialoildiffuser.webp",
  "Massage Gun": "/images/massagegun.webp",
  "Hair Dryer Professional": "/images/hyerdryerprofessional.webp",
  "Shower Head Filter": "/images/showerheadfilter.webp",
  "Face Steamer": "/images/facesteamer.webp",
  "Hydrating Sheet Mask (5-Pack)": "/images/Hydrating Sheet Mask (5-Pack).webp",
  "Vitamin C Glow Serum": "/images/Vitamin C Glow Serum.jpg", // .webp not available; uses provided .jpg
  "Moisturizing Face Cream": "/images/Moisturizing Face Cream.webp",
  "Waterproof Mascara": "/images/Waterproof Mascara.webp",
  "Velvet Matte Lipstick Duo": "/images/Velvet Matte Lipstick Duo.webp",
  "Makeup Organizer Bag": "/images/Makeup Organizer Bag.webp",
  "Facial Cleansing Brush": "/images/Facial Cleansing Brush.jpg",
  "Dry Shampoo Spray": "/images/Dry Shampoo Spray.webp",
  "Heat Protectant Hair Spray": "/images/Heat Protectant Hair Spray.webp",
  "Detangling Hair Serum": "/images/Detangling Hair Serum.avif", // .webp not available
  "Car Wipes Interior Cleaning Wipes": "/images/carvipes.webp",
  "Microfiber Cleaning Cloths (6-Pack)": "/images/microfibrecleaningcloth.webp",
  "Stainless Steel Car Wash Nozzle": "/images/stainlesssteelshower.webp",
  "Leather Honey Leather Conditioner": "/images/honeyleatherconditioner.webp",
  "Meguiar's Ultimate Compound": "/images/meguiresultimatecompound.webp",
  "Carfidant Scratch and Swirl Remover": "/images/carfidentscratchrepair.webp",
  "Cerakote Tire Coat Kit": "/images/cerakotetirecoat.webp",
  "Kicker Sprayable Cleaner & Protectant": "/images/kickersprayable.webp",
  "Plastic Restorer Trim Shine": "/images/plasticrestorer.webp",
  "Portable Car Vacuum Cleaner": "/images/vacuumcleaner.webp",
  "Quick Eraser Detailing Kit": "/images/quickeraserkit.webp",
  "Foam Wax Applicator Pads (6-Pack)": "/images/waxapplicatorpad.webp",
  "VRP Vinyl Rubber Protectant": "/images/VRPvinylrubber.webp",
  "303 Aerospace Protectant": "/images/aerospaceprotectentants.webp",
  "Makeup Brush Set": "/images/makeupbrushset.webp",
  "LED Makeup Mirror": "/images/LEDmakeupmirror.webp",
  "Hair Straightener": "/images/hairstraightner.webp",
  "Curling Iron Set": "/images/curlingironset.webp",
  "Wireless Earbuds": "/images/wirelessearbuds.webp",
  "Portable Bluetooth Speaker": "/images/portablebluetoothspeaker.webp",
  "USB-C Charging Cable": "/images/USBC-Chargingcable.webp",
  "Wireless Phone Charger": "/images/wirelessphonecharger.webp",
  "Smart Watch": "/images/smartwatch.webp",
  "Tablet Stand": "/images/tabletstand.webp",
  "Webcam HD": "/images/webcamHD.webp",
  "LED Desk Lamp": "/images/LEDdestlamp.webp",
  "Power Bank 20000mAh": "/images/powerbank2000mah.webp",
  "Phone Case": "/images/phonecase.webp",
  "Premium Dog Food": "/images/premiumdogfood.webp",
  "Cat Litter Box": "/images/catlitterbox.webp",
  "Pet Grooming Kit": "/images/petgroomingkit.webp",
  "Dog Leash & Harness Set": "/images/dogleashandharnessset.webp",
  "Cat Scratching Post": "/images/catscratchingpost.webp",
  "Pet Bed Deluxe": "/images/petbeddeluxe.webp",
  "Dog Chew Toys Set": "/images/dogchewtoyset.webp",
  "Automatic Pet Feeder": "/images/automaticpetfeeder.webp",
  "Pet Water Fountain": "/images/petwaterfountain.webp",
  "Pet Travel Carrier": "/images/pettravelcarrier.webp",
  "Ergonomic Office Chair": "/images/ergonomicofficechair.webp",
  "Standing Desk Converter": "/images/standingdeskconvertor.webp",
  "Dual Monitor Arm": "/images/dualmonitorarm.webp",
  "Desk Organizer Set": "/images/deskorgnizorset.webp",
  "Wireless Keyboard & Mouse Combo": "/images/wirelesskeyboardandmouse.webp",
  "All-in-One Printer": "/images/allinoneprinter.webp",
  "Office File Cabinet": "/images/officefilecabinet.webp",
  "Conference Room Speaker": "/images/microphoneforconforencerrom.webp",
  "Cable Management Tray": "/images/cabelmanagementtray.webp",
  "Whiteboard with Accessories": "/images/whiteboardwithaccessories.webp"
};

export type Product = {
  title: string;
  category: string;
  description: string;
  price: string;
  image?: string;
  slug: string;
  sku: string;
  highlights?: string[];
};

const baseProducts: Omit<Product, "image" | "slug" | "sku">[] = [
  { title: "Aveeno Baby Daily Moisture Lotion", category: "Baby Care", description: "Fragrance-free daily moisturizing lotion for delicate baby skin", price: "$11.99" },
  { title: "Baby Bath Tub", category: "Baby Care", description: "Ergonomic infant bath tub with sling-style support", price: "$24.99" },
  { title: "Gentle Baby Body Wash", category: "Baby Care", description: "Tear-free body wash formulated for newborns and sensitive skin", price: "$9.99" },
  { title: "Baby Grooming Kit", category: "Baby Care", description: "Complete set with nail clippers, file, brush, and safety scissors", price: "$14.99" },
  { title: "Silicone Baby Pacifiers (2-Pack)", category: "Baby Care", description: "Soft, BPA-free pacifiers with orthodontic design", price: "$7.99" },
  { title: "Baby Sunscreen SPF 50", category: "Baby Care", description: "Broad spectrum mineral sunscreen safe for babies", price: "$13.99" },
  { title: "Baby Crinkle Book with Teether", category: "Baby Care", description: "Soft fabric book with textures, crinkle pages, and teether corner", price: "$12.99" },
  { title: "Honest Shampoo & Body Wash", category: "Baby Care", description: "Gentle 2-in-1 cleanser with naturally derived ingredients", price: "$10.99" },
  { title: "Johnsons Baby Powder", category: "Baby Care", description: "Classic baby powder to keep skin soft and dry", price: "$6.99" },
  { title: "Soft Baby Hair Brush & Comb", category: "Baby Care", description: "Ultra-soft bristles for cradle cap and daily grooming", price: "$8.49" },
  { title: "Tear-Free Baby Shampoo", category: "Baby Care", description: "Mild cleansing shampoo designed to be gentle on eyes", price: "$9.49" },
  { title: "Digital Baby Thermometer", category: "Baby Care", description: "Fast-read digital thermometer with flexible tip", price: "$15.99" },
  { title: "Vapor Bath Drops", category: "Baby Care", description: "Soothing eucalyptus and lavender bath drops for stuffy noses", price: "$11.49" },
  { title: "Soothing Baby Bath Soak", category: "Baby Care", description: "Oatmeal and chamomile bath soak to calm dry, itchy skin", price: "$10.49" },
  { title: "Car Wipes Interior Cleaning Wipes", category: "Automotives", description: "Pre-moistened wipes for dashboards, consoles, and vinyl surfaces", price: "$8.99", highlights: ["Leaves low-gloss OEM look", "Safe on vinyl, plastic, and rubber", "Fresh scent, no greasy residue"] },
  { title: "Microfiber Cleaning Cloths (6-Pack)", category: "Automotives", description: "Ultra-soft microfiber towels for lint-free detailing and drying", price: "$12.99", highlights: ["350 GSM plush weave", "Edgeless design to reduce scratches", "Machine washable, color-safe"] },
  { title: "Stainless Steel Car Wash Nozzle", category: "Automotives", description: "Durable stainless wash nozzle with adjustable spray patterns", price: "$17.99", highlights: ["Solid stainless body", "Twist control from mist to jet", "Standard garden-hose threading"] },
  { title: "Leather Honey Leather Conditioner", category: "Automotives", description: "Deep-conditioning treatment to restore and protect leather seats", price: "$19.99", highlights: ["Restores suppleness and color", "Non-toxic, silicone-free formula", "Works on seats, steering wheels, and bags"] },
  { title: "Meguiar's Ultimate Compound", category: "Automotives", description: "Restores clarity by removing oxidation, scratches, and water spots", price: "$13.99", highlights: ["Clear coat safe", "Cuts fast but finishes glossy", "Use by hand or DA polisher"] },
  { title: "Carfidant Scratch and Swirl Remover", category: "Automotives", description: "All-in-one scratch remover and polish safe for all paint colors", price: "$18.99", highlights: ["Includes applicator pad", "Safe on clear coats and single stage", "Removes light scratches, swirls, and oxidation"] },
  { title: "Cerakote Tire Coat Kit", category: "Automotives", description: "Long-lasting ceramic tire coating for deep, dry-to-the-touch shine", price: "$24.99", highlights: ["Up to 3 months durability", "Dry, non-greasy satin finish", "Includes prep wipes for bonding"] },
  { title: "Kicker Sprayable Cleaner & Protectant", category: "Automotives", description: "Spray-and-wipe cleaner that leaves a UV-resistant satin finish", price: "$11.99", highlights: ["Cleans light dust and fingerprints", "Adds UV blockers", "Streak-free on interiors"] },
  { title: "Plastic Restorer Trim Shine", category: "Automotives", description: "Revives faded exterior plastics and trim with a dark, even finish", price: "$15.99", highlights: ["Restores black color", "Water-resistant finish", "Great for bumpers and cowl plastics"] },
  { title: "Portable Car Vacuum Cleaner", category: "Automotives", description: "Compact 12V vacuum with crevice tools for quick interior cleanups", price: "$34.99", highlights: ["Plugs into 12V socket", "Includes crevice and brush tools", "HEPA filter, easy-to-empty cup"] },
  { title: "Quick Eraser Detailing Kit", category: "Automotives", description: "Dual-density eraser sponges for spot-cleaning stains and grime", price: "$9.99", highlights: ["Two densities for paint and interior", "Great for rubber marks and tar", "Use damp—no chemicals needed"] },
  { title: "Foam Wax Applicator Pads (6-Pack)", category: "Automotives", description: "Dense foam pads for even wax, sealant, and dressing application", price: "$7.99", highlights: ["Tight-cell foam for even spread", "Reusable—hand wash and air dry", "Fits comfortably in hand"] },
  { title: "VRP Vinyl Rubber Protectant", category: "Automotives", description: "Versatile dressing for vinyl, rubber, and plastic surfaces", price: "$14.99", highlights: ["Water-based, sling-free", "Adjustable shine from satin to gloss", "Built-in UV protection"] },
  { title: "303 Aerospace Protectant", category: "Automotives", description: "UV protectant that restores color and prevents cracking on interiors and trim", price: "$16.99", highlights: ["SPF 40 UV protection", "Non-greasy matte finish", "Use on dashboards, trim, and rubber seals"] },
  { title: "Stainless Steel Cookware Set", category: "Home & Kitchen", description: "10-piece premium cookware set with non-stick coating", price: "$89.99" },
  { title: "Smart Coffee Maker", category: "Home & Kitchen", description: "Programmable coffee maker with timer and auto-shutoff", price: "$79.99" },
  { title: "Air Fryer XL", category: "Home & Kitchen", description: "Large capacity air fryer for healthy cooking", price: "$129.99" },
  { title: "Premium Knife Set", category: "Home & Kitchen", description: "8-piece professional chef knife set with block", price: "$149.99" },
  { title: "Stand Mixer Pro", category: "Home & Kitchen", description: "Heavy-duty stand mixer with multiple attachments", price: "$299.99" },
  { title: "Bamboo Cutting Board Set", category: "Home & Kitchen", description: "Eco-friendly bamboo cutting boards in 3 sizes", price: "$34.99" },
  { title: "Food Storage Container", category: "Home & Kitchen", description: "12-piece BPA-free glass container set with lids", price: "$49.99" },
  { title: "Electric Kettle", category: "Home & Kitchen", description: "Stainless steel electric kettle with temperature control", price: "$39.99" },
  { title: "Silicone Baking Mats", category: "Home & Kitchen", description: "Set of 2 non-stick silicone baking mats", price: "$19.99" },
  { title: "Kitchen Scale Digital", category: "Home & Kitchen", description: "Precision digital kitchen scale with LCD display", price: "$24.99" },
  { title: "Electric Toothbrush", category: "Health & Personal Care", description: "Rechargeable electric toothbrush with 3 modes", price: "$49.99" },
  { title: "Water Flosser", category: "Health & Personal Care", description: "Cordless water flosser with 3 pressure settings", price: "$69.99" },
  { title: "Digital Body Scale", category: "Health & Personal Care", description: "Smart scale with body composition analysis", price: "$39.99" },
  { title: "Essential Oil Diffuser", category: "Health & Personal Care", description: "Ultrasonic aromatherapy diffuser with LED lights", price: "$29.99" },
  { title: "Massage Gun", category: "Health & Personal Care", description: "Deep tissue percussion massager with 5 speeds", price: "$89.99" },
  { title: "Hair Dryer Professional", category: "Health & Personal Care", description: "Ionic hair dryer with multiple heat settings", price: "$59.99" },
  { title: "Shower Head Filter", category: "Health & Personal Care", description: "Chlorine filter shower head with 3 settings", price: "$34.99" },
  { title: "Face Steamer", category: "Health & Personal Care", description: "Facial steamer for deep pore cleansing", price: "$44.99" },
  { title: "Vitamin C Glow Serum", category: "Beauty", description: "Brightening facial serum with vitamin C and hyaluronic acid", price: "$32.99" },
  { title: "Moisturizing Face Cream", category: "Beauty", description: "Rich daily moisturizer for soft, hydrated skin", price: "$27.99" },
  { title: "Hydrating Sheet Mask (5-Pack)", category: "Beauty", description: "Soothing sheet masks infused with aloe and niacinamide", price: "$18.99" },
  { title: "Waterproof Mascara", category: "Beauty", description: "Smudge-proof mascara for long, lifted lashes", price: "$14.99" },
  { title: "Velvet Matte Lipstick Duo", category: "Beauty", description: "Long-wear matte lipsticks in two versatile shades", price: "$21.99" },
  { title: "Makeup Organizer Bag", category: "Beauty", description: "Travel-friendly cosmetic bag with multiple compartments", price: "$24.99" },
  { title: "Facial Cleansing Brush", category: "Beauty", description: "Gentle silicone cleansing brush with two-speed settings", price: "$34.99" },
  { title: "Dry Shampoo Spray", category: "Beauty", description: "Refreshes hair between washes with a clean, lightweight feel", price: "$13.99" },
  { title: "Heat Protectant Hair Spray", category: "Beauty", description: "Protects hair from styling tools up to 450°F", price: "$16.99" },
  { title: "Detangling Hair Serum", category: "Beauty", description: "Leave-in serum that tames frizz and adds shine", price: "$19.99" },
  { title: "Makeup Brush Set", category: "Beauty", description: "12-piece professional makeup brush collection", price: "$29.99" },
  { title: "LED Makeup Mirror", category: "Beauty", description: "Lighted makeup mirror with magnification", price: "$79.99" },
  { title: "Hair Straightener", category: "Beauty", description: "Ceramic flat iron with adjustable temperature", price: "$49.99" },
  { title: "Curling Iron Set", category: "Beauty", description: "3-barrel curling iron set with heat protection", price: "$39.99" },
  { title: "Wireless Earbuds", category: "Electronics", description: "Bluetooth 5.0 wireless earbuds with charging case", price: "$79.99" },
  { title: "Portable Bluetooth Speaker", category: "Electronics", description: "Waterproof Bluetooth speaker with 12-hour battery", price: "$59.99" },
  { title: "USB-C Charging Cable", category: "Electronics", description: "Fast charging USB-C cable, 6ft, 2-pack", price: "$14.99" },
  { title: "Wireless Phone Charger", category: "Electronics", description: "Qi-compatible wireless charging pad for smartphones", price: "$24.99" },
  { title: "Smart Watch", category: "Electronics", description: "Fitness tracker smartwatch with heart rate monitor", price: "$129.99" },
  { title: "Tablet Stand", category: "Electronics", description: "Adjustable aluminum tablet stand for desk", price: "$19.99" },
  { title: "Webcam HD", category: "Electronics", description: "1080p HD webcam with built-in microphone", price: "$49.99" },
  { title: "LED Desk Lamp", category: "Electronics", description: "Adjustable LED desk lamp with USB charging port", price: "$34.99" },
  { title: "Power Bank 20000mAh", category: "Electronics", description: "High-capacity portable power bank with fast charging", price: "$39.99" },
  { title: "Phone Case", category: "Electronics", description: "Protective phone case with tempered glass screen protector", price: "$19.99" },
  { title: "Premium Dog Food", category: "Pet supplies", description: "High-protein dry dog food with essential vitamins and minerals", price: "$39.99" },
  { title: "Cat Litter Box", category: "Pet supplies", description: "Covered cat litter box with odor control filter", price: "$29.99" },
  { title: "Pet Grooming Kit", category: "Pet supplies", description: "5-piece grooming kit with brush, comb, and nail clippers", price: "$24.99" },
  { title: "Dog Leash & Harness Set", category: "Pet supplies", description: "Adjustable harness with reflective leash for added safety", price: "$19.99" },
  { title: "Cat Scratching Post", category: "Pet supplies", description: "Sturdy scratching post with hanging toy to keep cats active", price: "$34.99" },
  { title: "Pet Bed Deluxe", category: "Pet supplies", description: "Plush washable pet bed for small and medium pets", price: "$44.99" },
  { title: "Dog Chew Toys Set", category: "Pet supplies", description: "Set of 6 durable chew toys for active dogs", price: "$22.99" },
  { title: "Automatic Pet Feeder", category: "Pet supplies", description: "Programmable pet feeder with portion control and timer", price: "$79.99" },
  { title: "Pet Water Fountain", category: "Pet supplies", description: "Circulating water fountain with filter for fresh water", price: "$49.99" },
  { title: "Pet Travel Carrier", category: "Pet supplies", description: "Soft-sided travel carrier approved for most airlines", price: "$59.99" },
  { title: "Ergonomic Office Chair", category: "Office Equipments", description: "Adjustable ergonomic chair with lumbar support and padded armrests", price: "$199.99" },
  { title: "Standing Desk Converter", category: "Office Equipments", description: "Height-adjustable desk converter for sitting or standing work", price: "$149.99" },
  { title: "Dual Monitor Arm", category: "Office Equipments", description: "Gas-spring dual monitor arm for 13–27 inch screens", price: "$89.99" },
  { title: "Desk Organizer Set", category: "Office Equipments", description: "Metal mesh organizer set with tray, pen holder, and file rack", price: "$39.99" },
  { title: "Wireless Keyboard & Mouse Combo", category: "Office Equipments", description: "Slim wireless keyboard and mouse set with 2.4GHZ receiver", price: "$49.99" },
  { title: "All-in-One Printer", category: "Office Equipments", description: "Wireless color printer with scan and copy functions", price: "$129.99" },
  { title: "Office File Cabinet", category: "Office Equipments", description: "3-drawer metal file cabinet with lockable drawers", price: "$159.99" },
  { title: "Conference Room Speaker", category: "Office Equipments", description: "USB/Bluetooth speakerphone optimized for online meetings", price: "$119.99" },
  { title: "Cable Management Tray", category: "Office Equipments", description: "Under-desk cable tray to hide and organize wires", price: "$29.99" },
  { title: "Whiteboard with Accessories", category: "Office Equipments", description: "Magnetic wall-mounted whiteboard with markers and eraser", price: "$59.99" }
];

export const products: Product[] = baseProducts.map((p, idx) => ({
  ...p,
  image: imageMap[p.title],
  slug: slugify(p.title),
  sku: `ARV-${String(idx + 1).padStart(4, "0")}`
}));

export const categories = Array.from(new Set(products.map((p) => p.category)));

export const productImageMap = imageMap;

export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
